/* Generated by tools/gen_swanstation_options.py - do not edit. SwanStation's core options. */
#pragma once

#define SS_OPT_COUNT 82

enum SsCategory
{
    SSC_CONSOLE,
    SSC_ENHANCEMENT,
    SSC_DISPLAY,
    SSC_PORT,
    SSC_ADVANCED,
    SSC_COUNT
};

typedef struct
{
    const char *key;   /* the libretro variable, swanstation_... */
    const char *label; /* English; tr() leaves it as it is when there is no translation */
    const char *help;
    unsigned char category, count, def;
    const char *const *values; /* what the core is given */
    const char *const *labels; /* what the menu shows */
} SsOpt;

extern const SsOpt SS_OPTS[SS_OPT_COUNT];
extern const char *const SS_CATEGORY_NAMES[SSC_COUNT];
