#!/usr/bin/env python3
# SwanStationPS5 - builds the interface icon font: a subset of Tabler Icons (MIT).
# SPDX-License-Identifier: GPL-3.0-or-later
"""
Keeps only the icons SwanStationPS5 draws and writes:
  assets/fonts/tabler-SwanStationPS5.ttf   the glyphs
  src/ui/icons_list.h             ICON_<NAME> = codepoint, for src/ui/icons.c

  pip install fonttools
  python tools/make_icon_font.py   (after adding a name to ICONS below)
"""
import re
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
VERSION = "3.31.0"
BASE = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}/dist"
CACHE = ROOT / "build" / "tabler"

ICONS = """
plus file-text device-tv sparkles device-gamepad-2 volume trophy books cpu info-circle player-play
device-floppy history code adjustments refresh door-exit chevron-right chevron-left
chevron-up chevron-down star heart clock world disc photo language settings arrows-sort
user wifi wifi-off download check x lock alert-triangle category list-details
rotate palette player-pause arrows-exchange keyboard hand-finger brand-speedtest
cards folder search layout-grid circle-check circle-x player-track-next
""".split()


def fetch(name: str) -> Path:
    path = CACHE / name
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(f"{BASE}/{name}", timeout=60) as r:
            path.write_bytes(r.read())
    return path


def main() -> None:
    css = fetch("tabler-icons.css").read_text(encoding="utf-8")
    pattern = re.compile(r'\.ti-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)"')
    codes = {name: int(code, 16) for name, code in pattern.findall(css)}
    missing = [n for n in ICONS if n not in codes]
    if missing:
        raise SystemExit(f"not in Tabler {VERSION}: {', '.join(missing)}")

    font = TTFont(fetch("fonts/tabler-icons.ttf"))
    options = subset.Options()
    options.notdef_outline = True
    options.name_IDs = ["*"]
    sub = subset.Subsetter(options)
    sub.populate(unicodes=[codes[n] for n in ICONS])
    sub.subset(font)
    out = ROOT / "assets" / "fonts" / "tabler-SwanStationPS5.ttf"
    font.save(out)

    header = ROOT / "src" / "ui" / "icons_list.h"
    lines = [
        "/* Generated by tools/make_icon_font.py from Tabler Icons " + VERSION + " (MIT). */",
        "#ifndef SwanStationPS5_ICONS_LIST_H",
        "#define SwanStationPS5_ICONS_LIST_H",
        "",
        "enum Icon",
        "{",
    ]
    for n in ICONS:
        lines.append(f"    ICON_{n.upper().replace('-', '_')} = 0x{codes[n]:x},")
    lines += ["};", "", f"#define ICON_COUNT {len(ICONS)}",
              "static const int ICON_CODEPOINTS[ICON_COUNT] = {"]
    lines += [f"    0x{codes[n]:x}," for n in ICONS]
    lines += ["};", "", "#endif", ""]
    header.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB, {len(ICONS)} icons) and {header}")


if __name__ == "__main__":
    main()
