#!/usr/bin/env bash
# SwanStationPS5 v2 - compiles src/platform/vk/shaders/*.{vert,frag} to SPIR-V and writes
# them as C arrays into src/platform/vk/shaders_spv.h (committed, so builds
# don't need a shader compiler). Run after changing a shader.
#
#   GLSLANG=/path/to/glslang bash tools/make-shaders.sh
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
glslang=${GLSLANG:-$(command -v glslang || command -v glslangValidator || echo "$root/build/glslang/bin/glslang.exe")}
python=${PYTHON:-$(command -v python || command -v python3)}
dir="$root/src/platform/vk/shaders"
out="$root/src/platform/vk/shaders_spv.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

to_c() {
    "$python" -c '
import sys, struct
data = open(sys.argv[1], "rb").read()
words = struct.unpack("<%dI" % (len(data) // 4), data)
print("static const uint32_t SPV_%s[] = {" % sys.argv[2].upper())
for i in range(0, len(words), 8):
    print("    " + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",")
print("};")' "$1" "$2"
}

{
    echo "/* Generated by tools/make-shaders.sh from src/platform/vk/shaders. Do not edit. */"
    echo "#ifndef SwanStationPS5_SHADERS_SPV_H"
    echo "#define SwanStationPS5_SHADERS_SPV_H"
    echo "#include <stdint.h>"
    for src in "$dir"/*.vert "$dir"/*.frag; do
        name=$(basename "$src" | tr '.' '_')
        "$glslang" -V --target-env vulkan1.1 -o "$tmp/$name.spv" "$src" >/dev/null
        to_c "$tmp/$name.spv" "$name"
    done
    echo "#endif"
} >"$out"
echo "wrote $out"
