#!/usr/bin/env bash
# SwanStationPS5 - compiles the GPU interface's shaders (src/platform/vk/shaders/ui.{vert,frag}) to SPIR-V and
# writes them as C arrays into src/platform/vk/shaders_ui_spv.h (committed, so builds don't need a shader
# compiler). Run after changing them.
#
#   GLSLANG=/path/to/glslang bash tools/make-ui-shaders.sh
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
glslang=${GLSLANG:-$(command -v glslang || command -v glslangValidator)}
python=${PYTHON:-$(command -v python3 || command -v python)}
dir="$root/src/platform/vk/shaders"
out="$root/src/platform/vk/shaders_ui_spv.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

to_c() {
    "$python" -c '
import sys, struct
data = open(sys.argv[1], "rb").read()
words = struct.unpack("<%dI" % (len(data) // 4), data)
print("static const uint32_t SPV_%s[] = {" % sys.argv[2].upper())
for i in range(0, len(words), 8):
    print("    " + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",")
print("};")' "$1" "$2"
}

{
    echo "/* Generated by tools/make-ui-shaders.sh from src/platform/vk/shaders/ui.*. Do not edit. */"
    echo "#ifndef SwanStationPS5_SHADERS_UI_SPV_H"
    echo "#define SwanStationPS5_SHADERS_UI_SPV_H"
    echo "#include <stdint.h>"
    for src in "$dir"/ui.vert "$dir"/ui.frag; do
        name=$(basename "$src" | tr '.' '_')
        "$glslang" -V --target-env vulkan1.1 -o "$tmp/$name.spv" "$src" >/dev/null
        to_c "$tmp/$name.spv" "$name"
    done
    echo "#endif"
} >"$out"
echo "wrote $out"
